export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const CHANGE_DATE_FILTER = 'CHANGE_DATE_FILTER'
export const CHANGE_SELECTED_FILTER = 'CHANGE_SELECTED_FILTER'
export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES'
export const LOAD_ARTICLE_BY_ID = 'LOAD_ARTICLE_BY_ID'


export const ADD_COMMENT = 'ADD_COMMENT'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'